services:
  db:
    image: mysql:8.0
    container_name: db_practica
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: sibw_db
      MYSQL_USER: sibw_user 
      MYSQL_PASSWORD: sibw_password
    volumes:
      - ./config/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: web_practica
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
      - ./templates:/usr/local/lib/php/templates
    ports:
      - "8080:80"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_practica
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - "8081:80"  # Lo ponemos en el puerto 8081 para no chocar con la web (8080)

  redis:
    image: redis:alpine
    container_name: redis_practica
    restart: always